# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c75d3ff55bb564d6c5c8c71f4d645fefc764bff8263f8cf3e86c2e6289c25cdd4b407d16f01286cc19bba63d316051b1d9ab89575c93502ff0999d73009a9025

test:
  secret_key_base: ca15a319ab4b8cefa618a25f5148f38b818d9359925a3bdbf80ff9608bb200929a25d7c22bdee3f5e9e2268dcc0dab11ebd94d774ab7fdd8d380ca7036a62d0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
